name: VuePress Deploy

on:
  push:
    branches: [ master ] # 触发条件：当有代码推送到 master 分支时

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境中运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # 检出代码

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16 # 设置 Node.js 版本为 16.x

    - name: Install pnpm
      run: |
        npm i -g pnpm # 安装 pnpm

    - name: Install dependencies
      run: pnpm install # 使用 pnpm 安装依赖

    - name: Build VuePress site
      run: pnpm run docs:build # 执行 VuePress 构建命令

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自动注入的 token
        publish_dir: ./dist # VuePress 构建输出的目录